version: "3.7"
services:
  rest:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    ports:
      - "8005:8005"
    env_file:
      - ./django/env/.env
    tty: 'true'
  vue:
    build:
      context: ./
      dockerfile: vue/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - rest


