version: "3.7"
services:
  rest:
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/app
    ports:
      - "8005:8005"
    tty: 'true'
    env_file:
      - ./django/env/dev.env
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./vue:/app:delegated
      - /app/node_modules
    tty: 'true'
    stdin_open: 'true'
  nginx:
    image: nginx:stable-alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf




