# Generated by Django 3.0.3 on 2020-02-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('Direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Direction')),
            ],
        ),
    ]
