# Generated by Django 3.0.3 on 2020-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='position',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
