# Generated by Django 3.0.3 on 2020-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20200301_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='importance',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
