# Generated by Django 3.0.3 on 2020-03-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_direction_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.Direction'),
        ),
    ]
