FROM node:lts-alpine as build-stage

WORKDIR /app

COPY ./vue/package.json .

RUN npm install

COPY ./vue .

RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html/dist

COPY --from=build-stage /app/src/assets /usr/share/nginx/html/src/assets

COPY --from=build-stage /app/index.html /usr/share/nginx/html/index.html

COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
